create table if not exists public.voice_attendance_submissions (
    submission_id bigint generated by default as identity primary key,
    student_id bigint not null,
    student_name text not null,
    subject_id bigint not null,
    subject_name text not null,
    subject_code text not null,
    submitted_at timestamptz not null default now(),
    latitude double precision not null check (latitude between -90 and 90),
    longitude double precision not null check (longitude between -180 and 180),
    location_accuracy_m double precision check (location_accuracy_m >= 0),
    voice_match_score double precision not null,
    status text not null default 'pending'
        check (status in ('pending', 'approved', 'rejected', 'superseded')),
    reviewed_at timestamptz,
    reviewed_by bigint
);

create index if not exists voice_attendance_pending_by_class
    on public.voice_attendance_submissions (subject_id, submitted_at desc)
    where status = 'pending';

create unique index if not exists one_pending_voice_attendance_per_student_class
    on public.voice_attendance_submissions (student_id, subject_id)
    where status = 'pending';

create index if not exists voice_attendance_by_student
    on public.voice_attendance_submissions (student_id, subject_id, submitted_at desc);

alter table public.voice_attendance_submissions enable row level security;
grant select, insert, update on public.voice_attendance_submissions to service_role;
grant usage, select on sequence public.voice_attendance_submissions_submission_id_seq to service_role;

create or replace function public.submit_voice_attendance(
    p_student_id bigint,
    p_student_name text,
    p_subject_id bigint,
    p_subject_name text,
    p_subject_code text,
    p_voice_match_score double precision,
    p_latitude double precision,
    p_longitude double precision,
    p_location_accuracy_m double precision
)
returns setof public.voice_attendance_submissions
language plpgsql
security invoker
set search_path = ''
as $$
begin
    update public.voice_attendance_submissions
    set status = 'superseded'
    where student_id = p_student_id
      and subject_id = p_subject_id
      and status = 'pending';

    return query
    insert into public.voice_attendance_submissions (
        student_id,
        student_name,
        subject_id,
        subject_name,
        subject_code,
        voice_match_score,
        latitude,
        longitude,
        location_accuracy_m
    )
    values (
        p_student_id,
        p_student_name,
        p_subject_id,
        p_subject_name,
        p_subject_code,
        p_voice_match_score,
        p_latitude,
        p_longitude,
        p_location_accuracy_m
    )
    returning *;
end;
$$;

revoke all on function public.submit_voice_attendance(
    bigint, text, bigint, text, text, double precision,
    double precision, double precision, double precision
) from public, anon, authenticated;

grant execute on function public.submit_voice_attendance(
    bigint, text, bigint, text, text, double precision,
    double precision, double precision, double precision
) to service_role;

create or replace function public.review_voice_attendance(
    p_submission_id bigint,
    p_teacher_id bigint,
    p_approved boolean
)
returns setof public.voice_attendance_submissions
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_submission public.voice_attendance_submissions%rowtype;
begin
    select submission.*
    into v_submission
    from public.voice_attendance_submissions as submission
    join public.subjects as subject
      on subject.subject_id = submission.subject_id
    where submission.submission_id = p_submission_id
      and submission.status = 'pending'
      and subject.teacher_id = p_teacher_id
    for update of submission;

    if not found then
        return;
    end if;

    update public.voice_attendance_submissions
    set status = case when p_approved then 'approved' else 'rejected' end,
        reviewed_at = now(),
        reviewed_by = p_teacher_id
    where submission_id = p_submission_id
    returning * into v_submission;

    if p_approved then
        insert into public.attendance_logs (
            student_id,
            subject_id,
            timestamp,
            is_present
        )
        values (
            v_submission.student_id,
            v_submission.subject_id,
            v_submission.submitted_at,
            true
        );
    end if;

    return next v_submission;
end;
$$;

revoke all on function public.review_voice_attendance(bigint, bigint, boolean)
    from public, anon, authenticated;
grant execute on function public.review_voice_attendance(bigint, bigint, boolean)
    to service_role;
